name: Waka Readme

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME_API }}
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_OS: "False"
